### PR TITLE
 Fix: Byte Parameter Type in Redshift

### LINKED ISSUE #210: Parameter Type Conversion Error with Byte Data
When running SQL queries with `byte` data in Redshift, it throws this error:  
```
{HY000} [Redshift][ODBC Driver] Parameter type conversion is not supported from 12 SQL type to -2 C type.
```

**Cause:**  
The problem is due to how the SQL type is being assigned in the code. The current logic sets the type to `SQL_VARCHAR`, even for `byte` data, which Redshift cannot handle.  

**Current code:**  
```go
// Incorrect logic
case p.isDescribed:
    sqltype = p.SQLType
```
This causes a type mismatch for `byte` parameters.  

---

### 💡 **Fix:**  
To solve this, we need to make sure `byte` data uses the correct type: `SQL_LONGVARBINARY`

**Fixed code:**  
```go
sqltype = api.SQL_LONGVARBINARY
```

Also [[go_ibm_db](https://github.com/ibmdb/go_ibm_db)] repo, which follows a similar structure as this repo, handles `byte` parameters correctly by mapping them to `SQL_BINARY`:  
```go
case []byte:
    ctype = api.SQL_C_BINARY
    b := make([]byte, len(d))
    copy(b, d)
    p.Data = b
    if len(d) > 0 {
        buf = unsafe.Pointer(&b[0])
    }
    buflen = api.SQLLEN(len(b))
    plen = p.StoreStrLen_or_IndPtr(buflen)
    size = api.SQLULEN(len(b))
    sqltype = api.SQL_BINARY
```
(Reference: [[go_ibm_db/param.go#L136-L147](https://github.com/ibmdb/go_ibm_db/blob/master/param.go#L136-L147)])  

We can do the similar in this repo to fix this issue.

### PR DESCRIPTION
**Pull request by Ajaysinh1290**
Description:

Fixes #210

This PR fixes an issue where byte parameters were wrongly mapped to SQL_VARCHAR, causing a type conversion error.

The fix ensures byte data uses SQL_LONGVARBINARY, which database can handle properly.

### CODE REVIEW

File: param.go [hunk 1]
```diff
@@ -144,22 +144,11 @@ func (p *Parameter) BindValue(h api.SQLHSTMT, idx int, v driver.Value, conn *Con
 		p.Data = b
 		if len(d) > 0 {
 			buf = unsafe.Pointer(&b[0])
-		} else {
-			buf = nil
-		}
+		}
```
Comment (alexbrainman) [inline param.go:147]: Use go fmt to format the code.

**Review by alexbrainman — CHANGES_REQUESTED** [review]
Looks reasonable, but please squash all commits into one and `go fmt` your changes.

Thank you.

Alex
